### ISSUE TITLE
How to use this work to cluster on my own dataset?

### ISSUE THREAD

**Issue by jzh1082** [thuiar/TEXTOIR#14]
I have a dataset with about 10% labeled data and I want to use this labeled data to do clustering on the rest. But the dataset in 'data' folder are all provided with ground truth label. How can I prepare data to use this work?

**Comment by HanleiZhang** [comment]
Hi, thanks for your watching in our works! You may achieve this goal with the pipeline framework in our another repo [TEXTOIR-DEMO](https://github.com/thuiar/TEXTOIR-DEMO)
