### ISSUE TITLE
Adding non-bert-based models to Open Intent Detection

### ISSUE THREAD

**Issue by mxnno** [thuiar/TEXTOIR#22]
Hi,
in your paper you wrote: "for example, the primary backbone is the pre-trained BERT (Devlin et al., 2019) model, and it supports adding new bert-based models with different downstream tasks."
But I would like to add other models for the Open Intent Detection part aswell, which are not bert-based, like Prototypical Networks, in order to compare more Open Intent Detection methods within this framework.
So is this possible?

**Comment by HanleiZhang** [comment]
Hi, you can add different models in the directory 'backbones'. Specifically, you need first config the basic model in the 'base.py' (such as pattern == 'bert') and then add new models with your basic backbones (such as 'bert.py').
