### ISSUE TITLE
Performance different from reported for SAE based models

### ISSUE THREAD

**Issue by zhang-yu-wei** [thuiar/TEXTOIR#23]
Hi!

Thanks for providing this excellent demo. However, when I tried to run some baseline models for unsupervised open intent discovery like "SAE-KM", "DCN" and "DEC", I found that the performance is different from what is reported in paper "Discovering New Intents with Deep Aligned Clustering".

For instance, with "DCN" model in this demo, after averaging 3 runs on "banking", I get **NMI 54.87, ARI 18.19, ACC 33.03**. As opposed **NMI 67.54, ARI 26.81, ACC 41.99** reported in the paper.

Notice that these models are all related with "SAE" embedding. I first wondered if it is because of different hyper-parameter choice. But the parameters I used strictly follows your implementation except the paths.

Also notice that I can not install all the dependencies by running `pip install -r requirements.txt`. Thus I have to change the versions for several packages by myself. The differences are:
1. keras-nightly==2.5.0.dev2021032900
2. tensorflow-gpu==2.5.1
3. Pillow==8.4.0
4. mkl-random==1.0.1.1
5. mkl-fft==1.0.6
6. numpy==1.19.5
7. remove torchaudio

To make it clearer in a future version, could you please:
1. add the performance list using your environment into README as a comparison for reproduction.
2. clean and remake the requirements.txt.

Thanks a lot! And appreciate your great work!

**Comment by HanleiZhang** [comment]
Hi, thanks for your recognition in our work! For DCN and DEC, you need to first train SAE and save the trained model and then, use the trained SAE model to perform DCN and DEC training.

**Comment by zhang-yu-wei** [comment]
Thanks for your quick reply!

It seems that the code will run "SAE" training automatically. But it still produces lower performance.
```
if os.path.exists(self.sae_feats_path):
    self.logger.info('Loading SAE features from %s' % self.sae_feats_path)
    self.sae.load_weights(self.sae_feats_path)
else:
    self.logger.info('SAE (emb) training start...')  
    self.sae.fit(self.tfidf_train, self.tfidf_train, epochs = args.num_train_epochs_SAE, batch_size = args.batch_size, shuffle=True, 
    validation_data=(self.tfidf_test, self.tfidf_test), verbose=1)
    self.logger.info('SAE (emb) training finished...') 

    if args.save_model:
        os.makedirs(self.sae_feats_path)
        self.sae.save_weights(self.sae_feats_path)
```

**Comment by mrFocusXin** [comment]
@zhang-yu-wei  Hi, "DCN" and "DEC"  does will run training automatically if the "self.sae_feats_path" not exists. However, some of DEC's or DCN's generic hyperparameters, such as Batch size, are not necessarily optimal for SAE.So you'd better train 
 "SAE" manually and save the model. And set "self.sae_feats_path"  to the SAE saved model. Hope to help you.

**Comment by zhang-yu-wei** [comment]
I see. As I would like to use this results, it would be great if you could maybe provide the pre-trained SAE features since it will save me a lot of time. Thanks! :-)

**Comment by mrFocusXin** [comment]
Of course, SAE's hyperparameter file path is in open_intent_discovery/configs/ sae.py.You can just run the open_intent_discovery/examples/run_SAE.sh and  make sure you add the parameter "save model" to the run_sae.sh file.
