### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by avesh-singh** [thuiar/TEXTOIR#33]
I was following the instructions given in Quick Start guide. I am using macOS Monterey 12.4 on my 13 inch Macbook Pro, M1, 2020.
I have not install cudatoolkit as it is not supported for my machine.

On doing `pip install -r requirements.txt` it is showing following error:
```
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.2.0 (from versions: 1.0.0.17, 1.0.2, 1.0.6)
ERROR: No matching distribution found for mkl-fft==1.2.0
```
I modified the requirements.txt file to install `mkl-fft>=1.2.0` but it is showing same error.

Is this solvable or shall I try installing it on CUDA supported machine?

**Comment by HanleiZhang** [comment]
I'm not sure that version 1.2.0 works in macOS as we install the libraries with Linux OS. Maybe you could try the suggested version (1.0.0.17, 1.0.2, 1.0.6) or install it with mirrors :)
