### ISSUE TITLE
any codes for the new method DA-ADB?

### ISSUE THREAD

**Issue by skykiseki** [thuiar/TEXTOIR#39]
would this be open-source in the future? I have read the paper but still wonder how it differs with ADB in details 

Learn a lot from the work, by the way. LOL

**Comment by HanleiZhang** [comment]
Hi, thanks for your attention! The codes of DA-ADB have been released. You can run the codes by executing the command in [run_DA-ADB.sh](https://github.com/thuiar/TEXTOIR/blob/main/open_intent_detection/examples/run_DA-ADB.sh).

**Comment by skykiseki** [comment]
> Hi, thanks for your attention! The codes of DA-ADB have been released. You can run the codes by executing the commands in [run_DA-ADB.sh](https://github.com/thuiar/TEXTOIR/blob/main/open_intent_detection/examples/run_DA-ADB.sh). The difference between DA-ADB and ADB can be found in [pretrain.py](https://github.com/thuiar/TEXTOIR/blob/main/open_intent_detection/methods/ADB/pretrain.py) and [bert.py](https://github.com/thuiar/TEXTOIR/blob/main/open_intent_detection/backbones/bert.py).

Too careless to see. Thx
