### ISSUE TITLE
对新意图检测和新意图发现两个方法论还是有点疑惑，求答疑

### ISSUE THREAD

**Issue by skykiseki** [thuiar/TEXTOIR#41]
看了了一下TEXTOIR-DEMO的代码方法以及整个的架构图，

我的理解是TEXTOIR用的intents detect（新意图检测）和intents discover（新意图发现）

如样本【A1,A2,B1,B2,B3,C1, UNK1,UNK2】
前者新意图检测（如ADB）主要是发现可能的新类别，即“找出”UNK1,UNK2

后者新意图发现（如DeepAlignCluster）主要是用有监督指导无监督聚类，我的问题在于，
如果我把上述的数据输入到DAC，最后会得到（A1,A2,UNK1）（B1,B2,B3）（C1）（UNK2）三个聚类结果

所以我对新意图发现的理解是，
Q1：该方法论可以实现“相同意图下的样本扩充”（如->A1,A2,UNK1）
Q2:   也可以实现可能的新类的发现与聚合（如UNK2），是不是我直接DAC就能解决新意图检测的目的了，只是效果差别而已

不知道这两个Q我理解的对不，

**Comment by HanleiZhang** [comment]
您好，感谢关注我们的工作。新意图检测是将所有为止意图看作一类UNK，能同时完成识别已知类检测UNK的目的。新意图发现主要是一个聚类问题，可以用来挖掘已知/新意图簇。关于您的问题，Q1在理论上是可以实现您提到的目的；关于Q2，如果直接用新意图发现方法，可以获得意图簇，但是无法实现已知类别的准确分类，对此，[TEXTOIR-DEMO](https://github.com/thuiar/TEXTOIR-DEMO)仓库提出了一种可能的实现框架，即理论上，在找到已知意图类别之后，可以利用发现的新意图簇用于新意图检测。本质上，新意图发现任务相较于检测任务更为困难，因为新意图类别以及数量都是完全未知的，也更符合真实应用场景。

**Comment by skykiseki** [comment]
> 您好，感谢关注我们的工作。新意图检测是将所有为止意图看作一类UNK，能同时完成识别已知类、检测UNK的目的。新意图发现任务主要是一个聚类问题，可以用来挖掘已知或者新意图簇。关于您的问题，Q1在理论上是可以实现您提到的目的；关于Q2，如果直接用新意图发现方法，可以获得意图簇，但是无法实现已知类别的准确分类，对此，[TEXTOIR-DEMO](https://github.com/thuiar/TEXTOIR-DEMO)仓库提出了一种可能的实现框架，即理论上，在找到已知意图类别之后，可以利用发现的新意图簇用于新意图检测。本质上，新意图发现任务相较于检测任务更为困难，因为新意图类别以及数量都是完全未知的，但更符合真实应用场景。

我还是对半监督的DAC最后的结果有点不明白，我推理用的是基于伪标签微调后的backbone再用kmeans聚类，而且这个聚类用到的K(基于predict_k产出)个数可能是小于ground truth实际的labels数量的（论文结果），跑出来的结果是km自己的label，那最终落地怎么应用这个km的label结果的呢？结果很可能就是上述说的，比如

（A1,A2,UNK1）（B1,B2,B3）（C1）（UNK2），同字母是一类，unk1是一类，unk2是一类


因为电脑最近坏了准备换个3070还在路上，之前一直看得都是您的detect的部分，也成功复现了不少结果都很不错。目前还没有跑过DAC的实验代码，但是看完了大致的代码和您的paper，希望能得到您的提前指点和交流

**Comment by HanleiZhang** [comment]
在您提供的例子中，可以理解成为了发现UNK2和UNK3所在的意图簇。新意图发现的结果就是得到聚类簇的信息，这样我们可以得到相似意图（包括已知和新意图类别）的数据，如果落地应用还需要对具有相似意图的数据统一打上一个标签，即我们不知道无监督数据的真实标签是什么。特别地，在计算ACC的时候，我们先利用匈牙利算法获得预测和真实标签的最大匹配映射，进而计算准确率。

**Comment by skykiseki** [comment]
> > 您好，感谢关注我们的工作。新意图检测是将所有为止意图看作一类UNK，能同时完成识别已知类、检测UNK的目的。新意图发现任务主要是一个聚类问题，可以用来挖掘已知或者新意图簇。关于您的问题，Q1在理论上是可以实现您提到的目的；关于Q2，如果直接用新意图发现方法，可以获得意图簇，但是无法实现已知类别的准确分类，对此，[TEXTOIR-DEMO](https://github.com/thuiar/TEXTOIR-DEMO)仓库提出了一种可能的实现框架，即理论上，在找到已知意图类别之后，可以利用发现的新意图簇用于新意图检测。本质上，新意图发现任务相较于检测任务更为困难，因为新意图类别以及数量都是完全未知的，但更符合真实应用场景。
> 
> 我还是对半监督的DAC最后的结果有点不明白，我推理用的是基于伪标签微调后的backbone再用kmeans聚类，而且这个聚类用到的K(基于predict_k产出)个数可能是小于ground truth实际的labels数量的（论文结果），跑出来的结果是km自己的label，那最终落地怎么应用这个km的label结果的呢？结果很可能就是上述说的，比如
> 
> （A1,A2,UNK1）（B1,B2,B3）（C1）（UNK2），（Unk3,UNK3)同字母是一类，unk1是一类，unk2是一类,UNK3是一类
> 
> DAC的目的主要是为了发现unk2和unk3么？
> 
> 因为电脑最近坏了准备换个3070还在路上，之前一直看得都是您的detect的部分，也成功复现了不少结果都很不错。目前还没有跑过DAC的实验代码，但是看完了大致的代码和您的paper，希望能得到您的提前指点和交流

对的，跟我预想的差不多，哈哈。多谢大佬。从这里学到了很多，
