### ISSUE TITLE
文档超链接错误

### ISSUE THREAD

**Issue by Maydaytyh** [thuiar/TEXTOIR#45]
![image](https://github.com/thuiar/TEXTOIR/assets/13815598/7146d9a4-ca8d-420f-9317-52c256e59351)
这里的超链接应该对应到 ./open_intent_detection/dataloaders/__init__.py，但似乎对应到了./open_intent_detection/configs/__init__.py，需修改

**Comment by HanleiZhang** [comment]
我们已经改正了文档中涉及到这个链接的两处地方，非常感谢您的指正！
