### ISSUE TITLE
Metric learning + Adaptive Decision Boundary

### ISSUE THREAD

**Issue by petrLorenc** [thuiar/TEXTOIR#46]
Hello, 
is it possible to include also this work - https://github.com/tgargiani/Adaptive-Boundary. I am one of the co-author and it would be interesting to compare with your methods (which were used as root idea for our algorithm)
Best regards Petr

**Comment by HanleiZhang** [comment]
Hi, thanks for your interests. You could integrate it into the TEXTOIR framework and pull request :)
