### ISSUE TITLE
Installation is terribly hard on OSX, is it supported?

### ISSUE THREAD

**Issue by robertleeplummerjr** [thuiar/TEXTOIR#47]
Just as an example:
```
conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch -c conda-forge
```

Results in:
```(textoir) robert.plummer@S86527 ~ % conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch -c conda-forge  
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.0

Current channels:

  - https://conda.anaconda.org/pytorch/osx-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Any easy workaround that could be stated within the readme?

**Comment by mrFocusXin** [comment]
> Just as an example:
> 
> ```
> conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch -c conda-forge
> ```
> 
> Results in:
> 
> ```
> Collecting package metadata (current_repodata.json): done
> Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - cudatoolkit=11.0
> 
> Current channels:
> 
>   - https://conda.anaconda.org/pytorch/osx-64
>   - https://conda.anaconda.org/pytorch/noarch
>   - https://conda.anaconda.org/conda-forge/osx-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://repo.anaconda.com/pkgs/main/osx-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/osx-64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.
> ```
> 
> Any easy workaround that could be stated within the readme?

Thank you for your interest in this work. Instead of installing cudatoolkit=11.0, you can install it directly from the pytorch website (https://pytorch.org/get-started/locally).
