### ISSUE TITLE
运行报错，想问下如何加载模型呢？无法自动下载模型。

### ISSUE THREAD

**Issue by Ratelsun** [thuiar/TEXTOIR#50]
如何手动添加模型呢？

**Comment by YoannCheung** [comment]
请问下你知道如何加载了吗？我没找到加载的路径，代码也不会自动下载的样子

**Comment by HanleiZhang** [comment]
您好，添加模型可以按照[readme](https://github.com/thuiar/TEXTOIR/tree/main/open_intent_detection)中Tutorials-b添加backbone（以open_intent_detection任务为例）。如果服务器没办法连上huggingface下载模型，则需要您手动下载模型并对应更新configs目录下参数文件以及backbones/base.py中加载预训练模型的函数
