### ISSUE TITLE
在您的文件中没有找到关于DA-ADB这一方法的内容

### ISSUE THREAD

**Issue by cdcdss** [thuiar/TEXTOIR#51]
![微信截图_20231216141945](https://github.com/thuiar/TEXTOIR/assets/107040374/66093e19-2387-460e-96d4-f0c3989a8b97)
只有您进行比对的十种方法

**Comment by HanleiZhang** [comment]
您好，DA-ADB方法在框架里是提供的，可以通过运行examples目录下的脚本[run_DA-ADB.sh](https://github.com/thuiar/TEXTOIR/blob/main/open_intent_detection/examples/run_DA-ADB.sh)实现。DA-ADB和ADB的不同点在于它们用的是不同的特征表示学习方法，不同的代码主要在于特征预训练脚本[pretrain.py](https://github.com/thuiar/TEXTOIR/blob/main/open_intent_detection/methods/ADB/pretrain.py) 和 模型脚本[bert.py](https://github.com/thuiar/TEXTOIR/blob/main/open_intent_detection/backbones/bert.py)。希望可以帮到您！

**Comment by cdcdss** [comment]
谢谢您的回复，我理解了



---原始邮件---
发件人: "Hanlei ***@***.***&gt;
发送时间: 2023年12月21日(周四) 下午5:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thuiar/TEXTOIR] 在您的文件中没有找到关于DA-ADB这一方法的内容 (Issue #51)




 
您好，DA-ADB方法在框架里是提供的，可以通过运行examples目录下的脚本run_DA-ADB.sh实现。DA-ADB和ADB的不同点在于它们用的是不同的特征表示学习方法，不同的代码主要在于特征预训练脚本pretrain.py 和 模型脚本bert.py。希望可以帮到您！
